import { DamageTypes, Skills } from "$lib/rpg/domain/config";
import {
  isCustom,
  type ContainerTemplate,
  type CustomTemplate,
  type Item,
  type ItemTemplate,
} from "../../infra/items";

/** Omit collapses a union, so it has to be applied to each member separately. */
type WithoutId<T> = T extends unknown ? Omit<T, "id"> : never;

/** The key is the id, so it is written once and every reference is checked. */
const catalogue = <T extends Record<string, WithoutId<ItemTemplate>>>(entries: T) =>
  Object.fromEntries(Object.entries(entries).map(([id, item]) => [id, { ...item, id }])) as unknown as {
    [K in keyof T]: T[K] & { id: K };
  };

export const ITEMS = catalogue({
  bone_saw: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: false,
  },
  screwdriver: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    twoHanded: false,
  },
  work_hammer: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.blunt },
    twoHanded: false,
  },
  small_dagger: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: false,
  },
  wrench: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.blunt },
    twoHanded: false,
  },
  knife: {
    kind: "melee",
    weight: 0.1,
    damage: { dice: { count: 1, sides: 20 }, flat: 20, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: false,
  },
  machete: {
    kind: "melee",
    weight: 0.5,
    damage: { dice: { count: 1, sides: 20 }, flat: 30, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: false,
  },
  sword: {
    kind: "melee",
    weight: 1,
    damage: { dice: { count: 1, sides: 20 }, flat: 30, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: false,
  },
  axe: {
    kind: "melee",
    weight: 2,
    damage: { dice: { count: 1, sides: 40 }, flat: 20, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: true,
  },
  chainsaw: {
    kind: "melee",
    weight: 4,
    damage: { dice: { count: 1, sides: 60 }, flat: 40, bonus: Skills.melee, type: DamageTypes.slash },
    twoHanded: true,
  },
  improv_metal_shield: {
    kind: "melee",
    weight: 5,
    damage: { flat: 10, type: DamageTypes.strike },
    twoHanded: false,
  },
  jcj_titanium_shield: {
    kind: "melee",
    weight: 8,
    damage: { flat: 16, type: DamageTypes.strike },
    twoHanded: false,
  },
  pistol: {
    kind: "ranged",
    weight: 1,
    hit: Skills.firearms,
    damage: { flat: 40, type: DamageTypes.pierce },
    range: 10,
    rate: 1,
    magazine: 12,
    reloadTurns: 1,
  },
  revolver: {
    kind: "ranged",
    weight: 1,
    hit: Skills.firearms,
    damage: { flat: 50, type: DamageTypes.pierce },
    range: 10,
    rate: 1,
    magazine: 6,
    reloadTurns: 2,
  },
  submachine_gun: {
    kind: "ranged",
    weight: 2,
    hit: Skills.firearms,
    damage: { flat: 25, type: DamageTypes.pierce },
    range: 12,
    rate: 6,
    magazine: 30,
    reloadTurns: 1,
  },
  semi_auto_shotgun: {
    kind: "ranged",
    weight: 2,
    hit: Skills.firearms,
    damage: { flat: 65, type: DamageTypes.pierce },
    range: 12,
    rate: 2,
    magazine: 10,
    reloadTurns: 1,
  },
  pump_shotgun: {
    kind: "ranged",
    weight: 2,
    hit: Skills.firearms,
    damage: { flat: 80, type: DamageTypes.pierce },
    range: 12,
    rate: 1,
    magazine: 6,
    reloadTurns: 1,
  },
  rifle: {
    kind: "ranged",
    weight: 2,
    hit: Skills.firearms,
    damage: { flat: 35, type: DamageTypes.pierce },
    range: 20,
    rate: 1,
    magazine: 6,
    reloadTurns: 1,
  },
  assault_rifle: {
    kind: "ranged",
    weight: 3,
    hit: Skills.firearms,
    damage: { flat: 40, type: DamageTypes.pierce },
    range: 30,
    rate: 4,
    magazine: 32,
    reloadTurns: 1,
  },
  battle_rifle: {
    kind: "ranged",
    weight: 3,
    hit: Skills.firearms,
    damage: { flat: 50, type: DamageTypes.pierce },
    range: 30,
    rate: 3,
    magazine: 24,
    reloadTurns: 1,
  },
  sniper_rifle: {
    kind: "ranged",
    weight: 5,
    hit: Skills.firearms,
    damage: { flat: 80, type: DamageTypes.pierce },
    range: 50,
    rate: 1,
    magazine: 4,
    reloadTurns: 1,
  },
  improvised_railgun: {
    kind: "ranged",
    weight: 1,
    hit: Skills.technology,
    damage: { flat: 75, type: DamageTypes.energy },
    range: 15,
    rate: 1,
    magazine: 1,
    reloadTurns: 4,
  },
  jcj_railgun: {
    kind: "ranged",
    weight: 2,
    hit: Skills.technology,
    damage: { flat: 100, type: DamageTypes.energy },
    range: 15,
    rate: 1,
    magazine: 1,
    reloadTurns: 2,
  },
  sentinel_gun: {
    kind: "ranged",
    weight: 4,
    hit: Skills.technology,
    damage: { type: DamageTypes.none },
    range: 5,
    rate: 1,
    magazine: 1,
    reloadTurns: 1,
  },
  pistol_ammo: { kind: "plain", weight: 0.5 },
  revolver_ammo: { kind: "plain", weight: 0.5 },
  submachine_gun_ammo: { kind: "plain", weight: 0.5 },
  semi_auto_shotgun_ammo: { kind: "plain", weight: 0.5 },
  pump_shotgun_ammo: { kind: "plain", weight: 0.5 },
  rifle_ammo: { kind: "plain", weight: 0.5 },
  assault_rifle_ammo: { kind: "plain", weight: 0.5 },
  battle_rifle_ammo: { kind: "plain", weight: 0.5 },
  sniper_rifle_ammo: { kind: "plain", weight: 0.5 },
  improvised_railgun_ammo: { kind: "plain", weight: 0.5 },
  jcj_railgun_ammo: { kind: "plain", weight: 0.5 },
  sentinel_gun_ammo: { kind: "plain", weight: 0.5 },
  grenade: {
    kind: "throwable",
    weight: 1,
    damage: { dice: { count: 1, sides: 60 }, flat: 20, bonus: Skills.explosives, type: DamageTypes.explosive },
    range: "1d75",
  },
  emp_grenade: { kind: "throwable", weight: 1, damage: { type: DamageTypes.none }, range: "1d75" },
  ninja_star: {
    kind: "throwable",
    weight: 0,
    damage: { flat: 10, bonus: Skills.melee, type: DamageTypes.pierce },
    range: "10",
  },
  bandage: { kind: "healing", weight: 0.05, worksOn: "humans" },
  first_aid_kit: { kind: "healing", weight: 0.5, worksOn: "humans" },
  medkit: { kind: "healing", weight: 1, worksOn: "humans" },
  surgical_kit: { kind: "healing", weight: 2, worksOn: "humans" },
  basic_repair_kit: { kind: "healing", weight: 2, worksOn: "drones" },
  repair_kit: { kind: "healing", weight: 2, worksOn: "drones" },
  jcj_sp_wd_repair_kit: { kind: "healing", weight: 3, worksOn: "drones" },
  solver_nanite_paste: { kind: "healing", weight: 0, worksOn: "both" },
  battery_pack: { kind: "plain", weight: 1 },
  oil_bottle_200ml: { kind: "liquid", weight: 0.1, capacity: 0.2, weightPerUnit: 0.8 },
  oil_bottle_500ml: { kind: "liquid", weight: 0.2, capacity: 0.5, weightPerUnit: 0.8 },
  oil_jug_1l: { kind: "liquid", weight: 0.4, capacity: 1, weightPerUnit: 0.8 },
  oil_jerrycan_10l: { kind: "liquid", weight: 0.6, capacity: 10, weightPerUnit: 0.8 },
  gasoline_jerrycan_10l: { kind: "liquid", weight: 0.6, capacity: 10, weightPerUnit: 0.6 },
  diesel_jerrycan_10l: { kind: "liquid", weight: 0.6, capacity: 10, weightPerUnit: 0.7 },
  stale_bread: { kind: "plain", weight: 0.2 },
  fresh_bread: { kind: "plain", weight: 0.3 },
  cold_pizza: { kind: "plain", weight: 0.5 },
  hot_pizza: { kind: "plain", weight: 0.5 },
  burger: { kind: "plain", weight: 0.6 },
  water_bottle_200ml: { kind: "liquid", weight: 0.1, capacity: 0.2, weightPerUnit: 1 },
  water_bottle_500ml: { kind: "liquid", weight: 0.2, capacity: 0.5, weightPerUnit: 1 },
  water_jug_1l: { kind: "liquid", weight: 0.4, capacity: 1, weightPerUnit: 1 },
  wd_head: { kind: "plain", weight: 10 },
  wd_leg: { kind: "plain", weight: 5 },
  wd_arm: { kind: "plain", weight: 5 },
  wd_body: { kind: "plain", weight: 40 },
  ad_head: { kind: "plain", weight: 8 },
  ad_leg: { kind: "plain", weight: 4 },
  ad_arm: { kind: "plain", weight: 4 },
  ad_body: { kind: "plain", weight: 30 },
  dd_arm: { kind: "plain", weight: 30 },
  dd_leg: { kind: "plain", weight: 30 },
  industrial_grade_glue: { kind: "plain", weight: 0.1 },
  tape: { kind: "plain", weight: 0.1 },
  box_of_screws: { kind: "plain", weight: 2 },
  silencer: { kind: "plain", weight: 0.1 },
  metal_sheet: { kind: "plain", weight: 0.4 },
  metal_rod: { kind: "plain", weight: 0.1 },
  gun_barrel: { kind: "plain", weight: 0.2 },
  gun_grip: { kind: "plain", weight: 0.1 },
  hollow_titanium_tube: { kind: "plain", weight: 0.1 },
  computer_parts: { kind: "plain", weight: 0.2 },
  nail: { kind: "plain", weight: 0.2 },
  high_energy_capacitor: { kind: "plain", weight: 0.2 },
  low_energy_capacitor: { kind: "plain", weight: 0.2 },
  human_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  worker_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  knife_tail: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  solver_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  solver_tail: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 2,
  },
  solver_claws: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 40 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  solver_stabbies: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  solver_translate: {
    kind: "innate",
    weight: 0,
    hit: Skills.absolute_solver,
    damage: { type: DamageTypes.none },
    range: 5,
  },
  solver_transform: {
    kind: "innate",
    weight: 0,
    hit: Skills.absolute_solver,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.absolute_solver, type: DamageTypes.energy },
    range: 5,
  },
  solver_teleport: {
    kind: "innate",
    weight: 0,
    hit: Skills.absolute_solver,
    damage: { type: DamageTypes.none },
    range: 15,
  },
  null_item: {
    kind: "innate",
    weight: 0,
    hit: Skills.absolute_solver,
    damage: { dice: { count: 1, sides: 100 }, bonus: Skills.absolute_solver, type: DamageTypes.energy },
    range: 5,
  },
  predator_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  predator_claws: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  avian_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 20 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  wings: { kind: "innate", weight: 0, hit: Skills.melee, damage: { type: DamageTypes.none }, range: 1 },
  small_claws: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  talon_dive: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  talon_strike: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  disassembly_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 40 }, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  sword_innate: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  disassembly_claws: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  chainsaw_innate: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 60 }, bonus: Skills.melee, type: DamageTypes.slash },
    range: 1,
  },
  submachine_gun_innate: {
    kind: "innate",
    weight: 0,
    hit: Skills.firearms,
    damage: { flat: 20, type: DamageTypes.pierce },
    range: 10,
  },
  laser: {
    kind: "innate",
    weight: 0,
    hit: Skills.firearms,
    damage: { flat: 25, type: DamageTypes.energy },
    range: 20,
  },
  missile: {
    kind: "innate",
    weight: 0,
    hit: Skills.firearms,
    damage: { flat: 16, type: DamageTypes.explosive },
    range: 20,
  },
  ninja_star_innate: {
    kind: "innate",
    weight: 0,
    hit: Skills.athletics,
    damage: { flat: 20, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 10,
  },
  emp: { kind: "innate", weight: 0, hit: Skills.technology, damage: { type: DamageTypes.none }, range: 5 },
  sentinel_flash: {
    kind: "innate",
    weight: 0,
    hit: Skills.technology,
    damage: { type: DamageTypes.none },
    range: 5,
  },
  sentinel_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { dice: { count: 1, sides: 30 }, flat: 20, type: DamageTypes.pierce },
    range: 1,
  },
  wasp_bite: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { flat: 6, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
  stinger: {
    kind: "innate",
    weight: 0,
    hit: Skills.melee,
    damage: { flat: 6, bonus: Skills.melee, type: DamageTypes.pierce },
    range: 1,
  },
});

export type ItemId = keyof typeof ITEMS;

/** Browsing order. `Innate` is hidden from players: those are body parts, not gear. */
export const ITEM_CATEGORIES: Record<string, ItemId[]> = {
  Melee: [
    "bone_saw",
    "screwdriver",
    "work_hammer",
    "small_dagger",
    "wrench",
    "knife",
    "machete",
    "sword",
    "axe",
    "chainsaw",
    "improv_metal_shield",
    "jcj_titanium_shield",
  ],
  Ranged: [
    "pistol",
    "revolver",
    "submachine_gun",
    "semi_auto_shotgun",
    "pump_shotgun",
    "rifle",
    "assault_rifle",
    "battle_rifle",
    "sniper_rifle",
    "improvised_railgun",
    "jcj_railgun",
    "sentinel_gun",
  ],
  Ammo: [
    "pistol_ammo",
    "revolver_ammo",
    "submachine_gun_ammo",
    "semi_auto_shotgun_ammo",
    "pump_shotgun_ammo",
    "rifle_ammo",
    "assault_rifle_ammo",
    "battle_rifle_ammo",
    "sniper_rifle_ammo",
    "improvised_railgun_ammo",
    "jcj_railgun_ammo",
    "sentinel_gun_ammo",
  ],
  Throwable: ["grenade", "emp_grenade", "ninja_star"],
  Healing: [
    "bandage",
    "first_aid_kit",
    "medkit",
    "surgical_kit",
    "basic_repair_kit",
    "repair_kit",
    "jcj_sp_wd_repair_kit",
    "solver_nanite_paste",
  ],
  Oil: [
    "battery_pack",
    "oil_bottle_200ml",
    "oil_bottle_500ml",
    "oil_jug_1l",
    "oil_jerrycan_10l",
    "gasoline_jerrycan_10l",
    "diesel_jerrycan_10l",
  ],
  "Human Food": [
    "stale_bread",
    "fresh_bread",
    "cold_pizza",
    "hot_pizza",
    "burger",
    "water_bottle_200ml",
    "water_bottle_500ml",
    "water_jug_1l",
  ],
  Resources: [
    "wd_head",
    "wd_leg",
    "wd_arm",
    "wd_body",
    "ad_head",
    "ad_leg",
    "ad_arm",
    "ad_body",
    "dd_arm",
    "dd_leg",
    "industrial_grade_glue",
    "tape",
    "box_of_screws",
    "silencer",
    "metal_sheet",
    "metal_rod",
    "gun_barrel",
    "gun_grip",
    "hollow_titanium_tube",
    "computer_parts",
    "nail",
    "high_energy_capacitor",
    "low_energy_capacitor",
  ],
  Innate: [
    "human_bite",
    "worker_bite",
    "knife_tail",
    "solver_bite",
    "solver_tail",
    "solver_claws",
    "solver_stabbies",
    "solver_translate",
    "solver_transform",
    "solver_teleport",
    "null_item",
    "predator_bite",
    "predator_claws",
    "avian_bite",
    "wings",
    "small_claws",
    "talon_dive",
    "talon_strike",
    "disassembly_bite",
    "sword_innate",
    "disassembly_claws",
    "chainsaw_innate",
    "submachine_gun_innate",
    "laser",
    "missile",
    "ninja_star_innate",
    "emp",
    "sentinel_flash",
    "sentinel_bite",
    "wasp_bite",
    "stinger",
  ],
};

export const CONTAINER_PREFABS: ContainerTemplate[] = [
  { name: "Fanny Pack", carry: 6 },
  { name: "Purse", carry: 8 },
  { name: "Suitcase", carry: 10 },
  { name: "Satchel", carry: 20 },
  { name: "Backpack", carry: 30 },
  { name: "Hiking Bag", carry: 40 },
  { name: "Shopping Cart", carry: 100 },
];

export const POCKETS: ContainerTemplate = { name: "Pockets", carry: null };

/** The definition behind a carried item, whether it came from the catalogue or the player. */
export function templateOf(item: Item): ItemTemplate | CustomTemplate | undefined {
  return isCustom(item.template) ? item.template : ITEMS[item.template as ItemId];
}

function round(value: number) {
  return parseFloat(value.toFixed(2));
}

/** A liquid's contents count toward its weight; every other kind is a fixed figure. */
export function itemWeight(item: Item) {
  const template = templateOf(item);
  if (!template) return 0;
  const contents = template.kind === "liquid" ? (item.current ?? 0) * template.weightPerUnit : 0;
  return round(template.weight + contents);
}

export function containerWeight(items: Item[]) {
  return round(items.reduce((total, item) => total + itemWeight(item), 0));
}
