import type { ContainerTemplate, ItemTemplate } from "./types";

const melee = (name: string, weight: number, damage: string, info: string | null = null, twoHanded = false) =>
  ({ kind: "melee", name, weight, damage, info, twoHanded }) satisfies ItemTemplate;

const ranged = (
  name: string,
  weight: number,
  hit: string,
  damage: string,
  range: number,
  rate: number,
  magazine: number,
  reloadTurns: number,
  info: string | null = null,
) => ({ kind: "ranged", name, weight, hit, damage, range, rate, magazine, reloadTurns, info }) satisfies ItemTemplate;

const RANGED = [
  ranged("Pistol", 1, "Firearms", "8 Pierce", 10, 1, 12, 1),
  ranged("Revolver", 1, "Firearms", "10 Pierce", 10, 1, 6, 2),
  ranged("Submachine Gun", 2, "Firearms", "6 Pierce", 12, 6, 30, 1, "-10 Hit every 3 meters"),
  ranged("Semi-Auto Shotgun", 2, "Firearms", "12 Pierce", 12, 2, 10, 1, "-10 Damage per meter"),
  ranged("Pump Shotgun", 2, "Firearms", "24 Pierce", 12, 1, 6, 1, "-20 Damage per meter"),
  ranged("Rifle", 2, "Firearms", "10 Pierce", 20, 1, 6, 1),
  ranged("Assault Rifle", 3, "Firearms", "10 Pierce", 30, 4, 32, 1),
  ranged("Battle Rifle", 3, "Firearms", "12 Pierce", 30, 3, 24, 1),
  ranged(
    "Sniper Rifle",
    5,
    "Firearms",
    "24 Pierce",
    50,
    1,
    4,
    1,
    "+2 Hit under 10m, -10 Hit above 10m, -20 Hit above 20m",
  ),
  ranged("Improvised Railgun", 1, "Technology", "22 Energy", 15, 1, 1, 4),
  ranged("JCJ Railgun", 2, "Technology", "28 Energy", 15, 1, 1, 2),
  ranged("Sentinel Gun", 4, "Technology", "Bootloops in a 5m cone", 5, 1, 1, 1, "Looking away costs 2 Reactions"),
];

export const CONTAINER_PREFABS: ContainerTemplate[] = [
  { name: "Fanny Pack", carry: 6 },
  { name: "Purse", carry: 8 },
  { name: "Suitcase", carry: 10 },
  { name: "Satchel", carry: 20 },
  { name: "Backpack", carry: 30 },
  { name: "Hiking Bag", carry: 40 },
  { name: "Shopping Cart", carry: 100 },
];

export const ITEM_PREFABS: Record<string, ItemTemplate[]> = {
  Melee: [
    melee("Bone Saw", 0.1, "1d20 + Strength Slash"),
    melee("Screwdriver", 0.1, "1d20 + Strength Pierce"),
    melee("Work Hammer", 0.1, "1d20 + Strength Blunt"),
    melee(
      "Small Dagger",
      0.1,
      "1d30 + Strength Slash",
      "Can be equipped without using an action. Can be used to perform an Assassination.",
    ),
    melee("Wrench", 0.1, "1d20 + Strength Blunt"),
    melee("Knife", 0.1, "1d20 + Strength + 20 Slash", "Can be used to perform an Assassination."),
    melee("Machete", 0.5, "1d20 + Strength + 30 Slash", "-10 Block"),
    melee("Sword", 1, "1d20 + Strength + 30 Slash", "-20 Hit, -20 Block"),
    melee("Axe", 2, "1d40 + Strength + 20 Slash", null, true),
    melee("Chainsaw", 4, "1d60 + Strength + 40 Slash", "+1 Hit, uses 200mL Oil per Hit", true),
    melee("Improv. Metal Shield", 5, "2 Strike", "-4 Block"),
    melee("JCJ Titanium Shield", 8, "4 Strike", "-6 Block"),
  ],
  Ranged: RANGED,
  Ammo: RANGED.map((weapon) => ({
    kind: "plain",
    name: weapon.name + " Ammo (" + weapon.magazine + ")",
    weight: 0.5,
  })),
  Throwable: [
    {
      kind: "throwable",
      name: "Grenade",
      weight: 1,
      damage: "1d60 + Explosives + 20 Explosive",
      range: "1d75",
      info: "Explodes after 1 Turn.",
    },
    {
      kind: "throwable",
      name: "EMP Grenade",
      weight: 1,
      damage: "Bootloops in a 5m cone",
      range: "1d75",
      info: "Explodes after 1 Turn.",
    },
    { kind: "throwable", name: "Ninja Star", weight: 0, damage: "10 + Strength Pierce", range: "10", info: null },
  ],
  Healing: [
    {
      kind: "healing",
      name: "Bandage",
      weight: 0.05,
      worksOn: "humans",
      heal: "20 HP",
      revive: null,
      requirements: null,
    },
    {
      kind: "healing",
      name: "First Aid Kit",
      weight: 0.5,
      worksOn: "humans",
      heal: "50 HP",
      revive: "Medicine check, difficulty is missing HP",
      requirements: null,
    },
    {
      kind: "healing",
      name: "MedKit",
      weight: 1,
      worksOn: "humans",
      heal: "75 HP",
      revive: "Yes",
      requirements: "Medicine Proficiency",
    },
    {
      kind: "healing",
      name: "Surgical Kit",
      weight: 2,
      worksOn: "humans",
      heal: "100 HP",
      revive: "Yes",
      requirements: "Medicine Expertise",
    },
    {
      kind: "healing",
      name: "Basic Repair Kit",
      weight: 2,
      worksOn: "drones",
      heal: "20 HP",
      revive: null,
      requirements: null,
    },
    {
      kind: "healing",
      name: "Repair Kit",
      weight: 2,
      worksOn: "drones",
      heal: "50 HP",
      revive: "Mechanics check, difficulty is missing HP",
      requirements: null,
    },
    {
      kind: "healing",
      name: "JCJ Sp. WD Repair Kit",
      weight: 3,
      worksOn: "drones",
      heal: "75 HP",
      revive: "Yes",
      requirements: "Mechanics Proficiency",
    },
    {
      kind: "healing",
      name: "Solver Nanite Paste",
      weight: 0,
      worksOn: "both",
      heal: "100% HP + 5 HP for 5 turns",
      revive: "Yes",
      requirements: null,
    },
  ],
  Oil: [
    { kind: "plain", name: "Battery Pack", weight: 1 },
    { kind: "liquid", name: "Oil Bottle (200mL)", weight: 0.1, capacity: 0.2, weightPerUnit: 0.8, current: 0.2 },
    { kind: "liquid", name: "Oil Bottle (500mL)", weight: 0.2, capacity: 0.5, weightPerUnit: 0.8, current: 0.5 },
    { kind: "liquid", name: "Oil Jug (1L)", weight: 0.4, capacity: 1, weightPerUnit: 0.8, current: 1 },
    { kind: "liquid", name: "Oil Jerrycan (10L)", weight: 0.6, capacity: 10, weightPerUnit: 0.8, current: 10 },
    { kind: "liquid", name: "Gasoline Jerrycan (10L)", weight: 0.6, capacity: 10, weightPerUnit: 0.6, current: 10 },
    { kind: "liquid", name: "Diesel Jerrycan (10L)", weight: 0.6, capacity: 10, weightPerUnit: 0.7, current: 10 },
  ],
  "Human Food": [
    { kind: "plain", name: "Stale Bread", weight: 0.2 },
    { kind: "plain", name: "Fresh Bread", weight: 0.3 },
    { kind: "plain", name: "Cold Pizza", weight: 0.5 },
    { kind: "plain", name: "Hot Pizza", weight: 0.5 },
    { kind: "plain", name: "Burger", weight: 0.6 },
    { kind: "liquid", name: "Water Bottle (200mL)", weight: 0.1, capacity: 0.2, weightPerUnit: 1, current: 0.2 },
    { kind: "liquid", name: "Water Bottle (500mL)", weight: 0.2, capacity: 0.5, weightPerUnit: 1, current: 0.5 },
    { kind: "liquid", name: "Water Jug (1L)", weight: 0.4, capacity: 1, weightPerUnit: 1, current: 1 },
  ],
  Resources: [
    { kind: "plain", name: "WD Head", weight: 10 },
    { kind: "plain", name: "WD Leg", weight: 5 },
    { kind: "plain", name: "WD Arm", weight: 5 },
    { kind: "plain", name: "WD Body", weight: 40 },
    { kind: "plain", name: "AD Head", weight: 8 },
    { kind: "plain", name: "AD Leg", weight: 4 },
    { kind: "plain", name: "AD Arm", weight: 4 },
    { kind: "plain", name: "AD Body", weight: 30 },
    { kind: "plain", name: "DD Arm", weight: 30 },
    { kind: "plain", name: "DD Leg", weight: 30 },
    { kind: "plain", name: "Industrial-Grade Glue", weight: 0.1 },
    { kind: "plain", name: "Tape", weight: 0.1 },
    { kind: "plain", name: "Box of Screws", weight: 2 },
    { kind: "plain", name: "Silencer", weight: 0.1 },
    { kind: "plain", name: "Metal Sheet", weight: 0.4 },
    { kind: "plain", name: "Metal Rod", weight: 0.1 },
    { kind: "plain", name: "Gun Barrel", weight: 0.2 },
    { kind: "plain", name: "Gun Grip", weight: 0.1 },
    { kind: "plain", name: "Hollow Titanium Tube", weight: 0.1 },
    { kind: "plain", name: "Computer Parts", weight: 0.2 },
    { kind: "plain", name: "Nail", weight: 0.2 },
    { kind: "plain", name: "High Energy Capacitor", weight: 0.2 },
    { kind: "plain", name: "Low Energy Capacitor", weight: 0.2 },
  ],
};

export const POCKETS: ContainerTemplate = { name: "Pockets", carry: 5 };
